import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import QueryProvider from '@/src/providers/QueryProvider';
import dynamic from 'next/dynamic';

// MSW는 개발 환경에서만 동적으로 import
const MswProvider = dynamic(() => import('@/mocks/MswProvider'), {
  ssr: false,
  loading: () => null,
});

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <MswProvider>
          <QueryProvider>
            <ToastContainer position="top-right" autoClose={1200} hideProgressBar={true} />
            {children}
          </QueryProvider>
        </MswProvider>
      </body>
    </html>
  );
}
