import type { Dashboard } from './types';

export const mockDashboards: Dashboard[] = [
  {
    id: '1',
    name: "bhzsk8rzxe's Dashboard Tue, Oct 28, 11...",
    description: 'Main monitoring dashboard for production services',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Platform', 'Backend'],
    popularity: 12,
    isFavorite: true,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '2',
    name: 'Postgres - Metrics',
    description: 'PostgreSQL database performance metrics',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Database'],
    popularity: 3,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '3',
    name: 'APM Datadog Agent (Trace Agent)',
    description: 'Trace agent monitoring and performance',
    author: { name: 'robot-datado...' },
    teams: ['APM'],
    popularity: 15,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '4',
    name: 'Storeding SRE',
    description: 'Site Reliability Engineering dashboard',
    author: { name: 'robot-datado...' },
    teams: ['SRE'],
    popularity: 6,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '5',
    name: 'APM Traces Estimated Usage',
    description: 'Estimated usage and costs for APM traces',
    author: { name: 'bhzsk8rzxe' },
    teams: ['APM', 'Finance'],
    popularity: 10,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '6',
    name: 'Docker - Overview',
    description: 'Container monitoring and metrics',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Platform'],
    popularity: 14,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
];
