import type { Dashboard } from './types';

export const mockDashboards: Dashboard[] = [
  {
    id: '1',
    name: 'Production Metrics',
    description: 'Main monitoring dashboard for production services',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Platform', 'Backend'],
    popularity: 12,
    isFavorite: true,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '2',
    name: 'Postgres - Metrics',
    description: 'PostgreSQL database performance metrics',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Database'],
    popularity: 3,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '3',
    name: 'Trace Agent Overview',
    description: 'Trace agent monitoring and performance',
    author: { name: 'robot-datado' },
    teams: ['APM'],
    popularity: 15,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '4',
    name: 'SRE Overview',
    description: 'Site Reliability Engineering monitoring',
    author: { name: 'robot-datado' },
    teams: ['SRE'],
    popularity: 6,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '5',
    name: 'APM Cost Usage',
    description: 'Estimated usage and APM costs',
    author: { name: 'bhzsk8rzxe' },
    teams: ['APM', 'Finance'],
    popularity: 10,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  {
    id: '6',
    name: 'Docker Overview',
    description: 'Container monitoring & metrics',
    author: { name: 'bhzsk8rzxe' },
    teams: ['Platform'],
    popularity: 14,
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  },
  // --- 추가 더미 9개 ---
  ...Array.from({ length: 9 }).map((_, i) => ({
    id: `${i + 7}`,
    name: `Custom Dashboard ${i + 1}`,
    description: 'User created dashboard',
    author: { name: 'user01' },
    teams: ['Platform'],
    popularity: Math.floor(Math.random() * 15),
    isFavorite: false,
    createdAt: '',
    updatedAt: '',
    widgets: [],
  })),
];
